### ISSUE TITLE
Import typo `.bitboard` to `chessengine.bitboard`

### ISSUE THREAD

**Issue by Montekkundan** [hrushikeshrv/chessengine#1]
![image](https://user-images.githubusercontent.com/87750128/192707742-3f327261-4e0c-4c2b-b094-0e44381695fe.png)

Instead of from .bitboard import Board it should be from chessengine.bitboard import Board in `play.py`

**Comment by Indrajeet-S** [comment]
Hey, I would like to manipulate this accordingly

**Comment by hrushikeshrv** [comment]
You're right, we should change the import to `from chessengine.bitboard import Board`. 👍🏻

**Comment by prasoonmhwr** [comment]
May I work on this if this is still open

**Comment by Montekkundan** [comment]
@prasoonmhwr i will be sending out the pr tomorrow at the start of the hacktoberfest, thank you for contributing please do contribute to other issues.

**Comment by prasoonmhwr** [comment]
@Montekkundan sure, no problem
