### ISSUE TITLE
Improve quality of opening book

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/chessengine#11]
Right now the engine parses 3 files in `chessengine.openings` at the start of each game to find good opening moves. The file `chessengine/openings/ViswanathanAnand.pgn` contains very few games, and we could probably replace it with a much larger file. Also, we should look for PGN files that contain a more diverse set of opening moves if possible.

**Comment by diwash007** [comment]
Hi Hrushikeshrv, can you please elaborate further on this issue?
I searched on the web and found some pretty large PGN files of games.

**Comment by hrushikeshrv** [comment]
Sure, right now the 3 PGN files in `chessengine.openings` are minimal, and cover mostly Queen's pawn and King's pawn openings. We should include diverse PGN files that include more openings, but at the same time, we should keep the total size of the files to less than, say, 100,000 games to keep the startup time reasonable.

I have found that http://www.pgnmentor.com/files.html#openings is a good place for PGN files. They have organized the files according to different openings, so you can choose a few files from there that contain a good number of moves and include them in the distribution.

**Comment by prasoonmhwr** [comment]
May I work on this

**Comment by Tatwansh** [comment]
Hey, I'm new to open source. May I work on this issue?

**Comment by hrushikeshrv** [comment]
Sorry @Tatwansh , I'll have to assign this to @prasoonmhwr since he commented first. Feel free to reach out to me if you need any help!

**Comment by prasoonmhwr** [comment]
@hrushikeshrv Thanks for assigning the issue, I know that we need to replace the existing pgn file with a file having more games, justs wanted to confirm how many pgn file do you need in this folder 3 or more.
