### ISSUE TITLE
Board scrolls up one line after each second move

### ISSUE THREAD

**Issue by zzril** [hrushikeshrv/chessengine#25]
Something seems wrong with the usage of the `clear_lines()` method. When playing white, after my own moves, the board stays adjusted correctly, but each time the computer makes a move, the board scrolls up 1 line in the terminal.

I think we need to clear one additional line at the end of the outer loop in `bitboard.py`.

It's the same behaviour on current main and on my recent Pull Request.

**Comment by hrushikeshrv** [comment]
Thanks, I refactored `Board.play` a little 👍🏻
