### ISSUE TITLE
Add support for en-passant moves

### ISSUE THREAD

**Issue by hrushikeshrv** [hrushikeshrv/chessengine#29]
This is one of the issues raised in #16. We should add support for en-passant moves. 

The function(s) for generating pawn moves - `chessengine.moves.get_white_pawn_moves` and `chessengine.moves.get_black_pawn_moves` provide an argument `allow_en_passant` that will also generate en-passant moves, which is currently set to `False` and never passed as `True`. I had added this argument as a temporary way to consider the generation of en-passant move, but this argument might now become redundant as we will implement proper support for en-passant moves.

The way I am thinking of approaching this is as follows - 
We will need to add an attribute to the `Board` class which would keep track of which pawn (if any) is allowed to make an en-passant move, and update that attribute on each move, which will probably need to be done in both `Board.move` and `Board.undo_move`. That attribute can then be checked inside `chessengine.moves.get_white_pawn_moves` and `chessengine.moves.get_black_pawn_moves` and en-passant moves can be generated, if valid.

**Comment by eemike07** [comment]
Hey, its maku.  Can you assign this one to me?

Thank you!!! :)

**Comment by eemike07** [comment]
Admittedly, this will take some time for me to digest.  
Just checked out the code and started playing with it.  

One notable concern that I have with implementing en-passant - Its kind of an "in-between" state.

**Comment by hrushikeshrv** [comment]
> Its kind of an "in-between" state.

I'm not quite sure what you mean. Could you elaborate?

**Comment by eemike07** [comment]
There needs to be a way to pass in the previous move and check if the  pawn that's currently being moved is applicable to en-passant.  The "in-between" state that I'm referring to is that there needs to be a look ahead and check on that pawn performing the en-passant results in King exposed (making an illegal move).

**Comment by hrushikeshrv** [comment]
> There needs to be a way to pass in the previous move and check if the pawn that's currently being moved is applicable to en-passant.

Yes, for this, we could probably use the `Board.moves` list that stores all the moves made in the game so far - [see docs](https://chessengine.readthedocs.io/en/latest/chessboard.html#attributes-for-chess-board).

For the second point you mention, that is an issue with not just pawns, but all pieces. Currently, none of the pieces check if a move they are making results in exposing the king. Fixing that efficiently will require some more thinking and (probably) a more global fix, because checking each time if the king would be in check for each move generated by each piece would be very inefficient and slow down the forward search (at least I can't think of a way to check that way efficiently). However, if you have any ideas on how we could perform that check, please let me know :)

**Comment by eemike07** [comment]
I plan on working on this on Sunday - if someone else wants to take it up prior to, feel free.
Otherwise, I'll commit this to my Sunday code-and-coffee :)

**Comment by eemike07** [comment]
Hey, I'm gonna have to abandon this one.  

Unless I can set up a debugger, I don't really have a way of implementing this.

**Comment by hrushikeshrv** [comment]
No problem, I'll take it up 👍🏻
