### ISSUE TITLE
Refactoring: Parser class

### ISSUE THREAD

**Issue by zzril** [hrushikeshrv/chessengine#31]
The `parse` method in `parser.py` is somewhat redundant. I've already made a quick fix (see #32 ), but would also like to take this moment to ask how we should go on with refactorings in general?

Is it ok to do small refactorings like this one, possibly even without raising an issue about it first? Or should we refrain from doing so, for not introducing too many merge conflicts?

**Comment by hrushikeshrv** [comment]
I would say raising an issue would be a good idea, as you mentioned, to prevent merge conflicts if people are working on the same method 👍🏻
