### ISSUE TITLE
Refactoring: Remove redundancies in bitboard.play and bitboard.play_pvp

### ISSUE THREAD

**Issue by zzril** [hrushikeshrv/chessengine#37]
We've added player-vs-player support with #36 .  
However, the newly added `play_pvp` method in `bitboard.py` is to a large extend the same as the `play` method (in the same module).

Some refactoring would probably help here, to make future changes to the play methods easier. At first glance, this does not seem completely trivial, though.

**Comment by amcintosh** [comment]
I would be interested in working on this.

**Comment by hrushikeshrv** [comment]
I agree. Thanks, @amcintosh, I'll assign this to you.

I noticed that as I was implementing the `play_pvp` method, but the simple `lines_printed` variable made it harder for me to refactor both the methods effectively. As a start, maybe we could add a function/method to get the move the user wants to make, and call that in both play methods. I'm still not sure how we would track the number of lines printed in that case, though. 

 Please let me know if you need any more info from me 👍🏻

**Comment by zzril** [comment]
@hrushikeshrv Could this be solved using a global variable `lines_printed` that is changed from within these functions?
Possibly one could even write a wrapper for Python's `print()` function that simply passes its arguments to the actual `print()` function, and updates the global variable accordingly. Then all other functions would always call the wrapper during the play loop.

**Comment by hrushikeshrv** [comment]
@zzril yeah, that could be a good start.

**Comment by amcintosh** [comment]
Hi. I've done a bit of a refactor moving out the common code. I haven't really touched the print_lines code other than returning it in the refactored method. I'm actually wondering if maybe using something like `click` and a [clear-screen method](https://click.palletsprojects.com/en/7.x/utils/#screen-clearing) might be a good choice, but adding a new dependency and refactoring the user I/O seems like a separate task.

**Comment by hrushikeshrv** [comment]
Yeah, for now, I think the refactor you have done looks good. I would like to avoid adding a dependency as much as we can, so as long as it doesn't become restrictive to work with the `play` methods without more refactoring, I think it should be fine.
